export const columns = [
  { id: 1, label: 'Trip ID', slug: 'trip_name', is_active: true },
  { id: 2, label: 'Customer Name', slug: 'customer_name', is_active: true },
  { id: 3, label: 'Operations Owner', slug: 'operations_owner', is_active: true },
  { id: 4, label: 'Created Date', slug: 'created_date', is_active: true },
  { id: 5, label: 'Start Date', slug: 'start_date', is_active: true },
  { id: 6, label: 'Finish Date', slug: 'end_date', is_active: true },
  { id: 7, label: 'Business Trip Price', slug: 'business_trip_price', is_active: true },
  { id: 8, label: 'Business Gross Margin (%)', slug: 'business_cost_margin_per', is_active: true },
  { id: 9, label: 'Travellers', slug: 'travellers', is_active: true },
  { id: 10, label: 'Start Location', slug: 'start_location', is_active: true },
  { id: 11, label: 'Finish Location', slug: 'end_location', is_active: true },
  { id: 12, label: 'General Status', slug: 'general_status', is_active: true },
  { id: 13, label: 'Accommodation', slug: 'accommodation_status', is_active: true },
  { id: 14, label: 'Transfers', slug: 'normal_status', is_active: true },
  { id: 15, label: 'Luggage', slug: 'luggage_status', is_active: true },
  { id: 16, label: 'Other', slug: 'other_status', is_active: true },
  { id: 17, label: 'Voucher And Dossiers', slug: 'voucher_status', is_active: true },
  { id: 18, label: 'Travel Insurance', slug: 'insurance_status', is_active: true },
  { id: 19, label: 'Pending Tasks', slug: 'pending_tasks', is_active: true },
  { id: 20, label: 'Overdue Tasks', slug: 'overdue_tasks', is_active: true },
  { id: 21, label: 'Tags', slug: 'tags', is_active: true },
  { id: 22, label: 'Prepayment', slug: 'pending_prepayments', is_active: true },
  { id: 23, label: 'Invoice Number', slug: 'invoice_number', is_active: true },
  { id: 24, label: 'Invoice Date', slug: 'invoice_date', is_active: true },
  { id: 25, label: 'Direct Costs', slug: 'cost', is_active: true },
  { id: 26, label: 'Insurance Costs', slug: 'insurance_cost', is_active: true },
  { id: 27, label: 'Business Gross Margin (€)', slug: 'business_cost_margin', is_active: true }
]
